### ISSUE TITLE
support perl

### ISSUE THREAD

**Issue by antonikonovalov** [laughedelic/LoadFileToRepl#18]

**Comment by kaiorafael** [comment]
Hi, after so many years, have you found the answer already?

If not, can you describe better what you wanna do using Perl shell?

Are you looking for how to use http://search.cpan.org/dist/Devel-REPL/lib/Devel/REPL.pm ?

**Comment by laughedelic** [comment]
Hi @kaiorafael. Are you asking me or @antonikonovalov?

I'm personally not interested in using Perl, so I'm not going to implement this. But if you know how to load a file in that Perl shell (assuming this is what is used by SublimeREPL for Perl), you're welcome to submit a pull-request with the command.

**Comment by kaiorafael** [comment]
I am asking from you @laughedelic you have a HackOctoberFest ticket.

I dont use Sublime, but I can take a look

cheers.

**Comment by laughedelic** [comment]
OK. The label is there meaning that anyone can send a PR to solve this and participate in Hactoberfest (and get a free 👕 ). 
I don't using Sublime either 😂 But the plugin works and I still maintain it and accept pull-requests. 

If you are willing to try, check PRs linked in the [table](https://github.com/laughedelic/LoadFileToRepl#description) as examples of what you need to change here.

**Comment by BVBee** [comment]
It seems that the plugin doesn't work in win10

**Comment by laughedelic** [comment]
@BVBee is it related to Perl? (which is, obviously, not supported) or is it a general issue on win10? is it's the latter, please, open a new issue and provide more details.

I'm going to close this issue since it only generates confusion..

**Comment by BVBee** [comment]
It even doesn't work well on my mac
