### ISSUE TITLE
Change directory before loading file

### ISSUE THREAD

**Issue by a-baygeldin** [laughedelic/LoadFileToRepl#33]
When I import some module in Haskell, current directory is not changing. I have to explicitly change the directory with ":cd someDirectory". So, it's a good idea to start a GHCi in the same directory that the current file is located in.

**Comment by laughedelic** [comment]
Hi @a-baygeldin! This is likely to be an issue related to SublimeREPL, not this plugin. Take a look at this issue: #25

**Comment by a-baygeldin** [comment]
Thanks for explanation, now I realize that this issue is not related specifically to this plugin :) Unfortunatly, related issue didn't help me, but I changed "Packages\SublimeREPL\config\Haskell\Main.sublime-menu" a little so that REPL runs in folder which is convinient to me instead Sublime Text folder.
